Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.v8.try/v8_linux64_rel_ng JOB_FAILED https://cr-buildbucket.appspot.com/build/8863822697294227680
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [90/1425] CXX obj/mksnapshot/mksnapshot.o
    FAILED: obj/mksnapshot/mksnapshot.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../src/snapshot/mksnapshot.cc:12:
    In file included from ../../src/codegen/assembler-arch.h:8:
    In file included from ../../src/codegen/assembler.h:47:
    In file included from ../../src/codegen/reloc-info.h:10:
    In file included from ../../src/objects/code.h:9:
    In file included from ../../src/codegen/handler-table.h:9:
    ../../src/common/assert-scope.h:88:9: error: unused variable 'unused' [-Werror,-Wunused-variable]
    int unused[]{(is_allowed &= Scopes::IsAllowed(), 0)...};
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_fuchsia_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8863822697294227808
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [95/2247] CXX clang_x64/obj/mksnapshot/mksnapshot.o
    FAILED: clang_x64/obj/mksnapshot/mksnapshot.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../src/snapshot/mksnapshot.cc:12:
    In file included from ../../src/codegen/assembler-arch.h:8:
    In file included from ../../src/codegen/assembler.h:47:
    In file included from ../../src/codegen/reloc-info.h:10:
    In file included from ../../src/objects/code.h:9:
    In file included from ../../src/codegen/handler-table.h:9:
    ../../src/common/assert-scope.h:88:9: error: unused variable 'unused' [-Werror,-Wunused-variable]
    int unused[]{(is_allowed &= Scopes::IsAllowed(), 0)...};
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_linux_arm64_rel_ng JOB_FAILED https://cr-buildbucket.appspot.com/build/8863822697294227632
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [153/1366] CXX obj/mksnapshot/mksnapshot.o
    FAILED: obj/mksnapshot/mksnapshot.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../src/snapshot/mksnapshot.cc:12:
    In file included from ../../src/codegen/assembler-arch.h:8:
    In file included from ../../src/codegen/assembler.h:47:
    In file included from ../../src/codegen/reloc-info.h:10:
    In file included from ../../src/objects/code.h:9:
    In file included from ../../src/codegen/handler-table.h:9:
    ../../src/common/assert-scope.h:88:9: error: unused variable 'unused' [-Werror,-Wunused-variable]
    int unused[]{(is_allowed &= Scopes::IsAllowed(), 0)...};
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_linux64_pointer_compression_rel_ng JOB_FAILED https://cr-buildbucket.appspot.com/build/8863822697294227696
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [85/1355] CXX obj/mksnapshot/mksnapshot.o
    FAILED: obj/mksnapshot/mksnapshot.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../src/snapshot/mksnapshot.cc:12:
    In file included from ../../src/codegen/assembler-arch.h:8:
    In file included from ../../src/codegen/assembler.h:47:
    In file included from ../../src/codegen/reloc-info.h:10:
    In file included from ../../src/objects/code.h:9:
    In file included from ../../src/codegen/handler-table.h:9:
    ../../src/common/assert-scope.h:88:9: error: unused variable 'unused' [-Werror,-Wunused-variable]
    int unused[]{(is_allowed &= Scopes::IsAllowed(), 0)...};
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_linux64_verify_csa_rel_ng JOB_FAILED https://cr-buildbucket.appspot.com/build/8863822697294227648
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [171/1355] CXX obj/mksnapshot/mksnapshot.o
    FAILED: obj/mksnapshot/mksnapshot.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../src/snapshot/mksnapshot.cc:12:
    In file included from ../../src/codegen/assembler-arch.h:8:
    In file included from ../../src/codegen/assembler.h:47:
    In file included from ../../src/codegen/reloc-info.h:10:
    In file included from ../../src/objects/code.h:9:
    In file included from ../../src/codegen/handler-table.h:9:
    ../../src/common/assert-scope.h:88:9: error: unused variable 'unused' [-Werror,-Wunused-variable]
    int unused[]{(is_allowed &= Scopes::IsAllowed(), 0)...};
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run