Update patch set 2
Patch Set 2:

> Patch Set 1: Commit-Queue+2

We got this failure on our buildbots:

FAILED: obj/test/unittests/unittests_sources/macros-unittest.o 
mipsel-linux-gnu-g++ -MMD -MF obj/test/unittests/unittests_sources/macros-unittest.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DV8_INTL_SUPPORT -DENABLE_HANDLE_ZAPPING -DV8_USE_SNAPSHOT -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_CONCURRENT_MARKING -DV8_TARGET_ARCH_MIPS -DCAN_USE_FPU_INSTRUCTIONS -D__mips_hard_float=1 -DCAN_USE_FPU_INSTRUCTIONS -D_MIPS_ARCH_MIPS32R2 -DFPU_MODE_FP32 -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DUNIT_TEST -I../.. -Igen -I../../include -Igen/include -I../.. -I../../testing/gtest/include -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../include -I../../testing/gmock_custom -I../../testing/gmock/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -pthread -EL -mips32r2 -Wa,-mips32r2 -mfp32 -mhard-float -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-missing-field-initializers -Wno-unused-parameter -fno-omit-frame-pointer -g0 -fno-builtin-abs -fvisibility=hidden -Wno-strict-overflow -O3 -fno-ident -fdata-sections -ffunction-sections -std=gnu++14 -Wno-narrowing -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -c ../../test/unittests/base/macros-unittest.cc -o obj/test/unittests/unittests_sources/macros-unittest.o
In file included from ../../test/unittests/base/macros-unittest.cc:5:0:
../../src/base/macros.h:258:3: error: static assertion failed: NonCopyableshould not be trivially copyable
   static_assert(!::v8::base::is_trivially_copyable<T>::value, \
   ^
../../test/unittests/base/macros-unittest.cc:40:1: note: in expansion of macro ‘ASSERT_NOT_TRIVIALLY_COPYABLE’
 ASSERT_NOT_TRIVIALLY_COPYABLE(NonCopyable);


https://v8.imgtec.com/bbv8/builders/Target%20-%20edge%20-%20builder/builds/18248/steps/compile/logs/stdio

Patch-set: 2
CC: Gerrit User 1192879 <1192879@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>