[parser] Improve parse error message for missing name in FunctionDeclaration
Added a new Error Message for Missing Function Name.
Added the token var to the list of reserved tokens.

The program:

function(){}

...now produces:
	SyntaxError: Function statements require a valid function name.

...instead of:
	SyntaxError: Unexpected Token (

Bug: v8:3698, v8:6513
Change-Id: I3c12dfcfe80b94209aa9af434ae1d212970cf362