Update patch set 1
Patch Set 1:

I managed to reproduce the same issue on X64 using gcc version 4.9.4 (Ubuntu 4.9.4-2ubuntu1~14.04.1) 

To reproduce: 
gn gen out.gn/x64_debug --args='is_debug=true target_cpu="x64" is_clang=false use_cxx11=true'
nice ninja -C out.gn/x64_debug/ d8

The compiler  will complain about  calling memset with argument 0 for length, fix it manually.

You will get the following error:

python "../../build/toolchain/gcc_link_wrapper.py" --output="./d8" -- g++ -pie -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -Werror -Wl,--gdb-index -rdynamic -nodefaultlibs --sysroot=../../build/linux/debian_sid_amd64-sysroot -L../../build/linux/debian_sid_amd64-sysroot/usr/local/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_sid_amd64-sysroot/usr/local/lib/x86_64-linux-gnu -L../../build/linux/debian_sid_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_sid_amd64-sysroot/lib/x86_64-linux-gnu -L../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,-rpath=\$ORIGIN/. -Wl,-rpath-link=. -Wl,-O2 -Wl,--gc-sections -o "./d8" -Wl,--start-group @"./d8.rsp" ./libv8.so ./libv8_libbase.so ./libv8_libplatform.so ./libicui18n.so ./libicuuc.so ./libc++.so -Wl,--end-group   -lc -lgcc_s -lm -lrt -ldl -lpthread 
../../src/ostreams.h:24: error: undefined reference to 'vtable for v8::internal::OFStreamBase'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../../src/ostreams.h:24: error: undefined reference to 'vtable for v8::internal::OFStreamBase'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../../src/ostreams.h:24: error: undefined reference to 'vtable for v8::internal::OFStreamBase'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Patch-set: 1
Reviewer: Gerrit User 1192879 <1192879@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>