Update patch set 5
Patch Set 5:

This breaks compilation on Windows VS2015, so it breaks nodejs:

```
"C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj" (Build target) (1) ->
(ClCompile target) ->
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(88): error C3250: 'upper_half': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(89): error C3250: 'next_value': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(90): error C3250: 'add': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(91): error C3250: 'next_bits': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(92): error C3256: 'next_value': variable use does not produce a constant expression [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(92): error C3256: 'add': variable use does not produce a constant expression [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(76): error C3259: 'constexpr' functions can only have one return statement [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(120): error C3250: 'u': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(121): error C3256: 'u': variable use does not produce a constant expression [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
  C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(40): error C3250: 'mask': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]

    51 Warning(s)
    10 Error(s)
```

Patch-set: 5
CC: Gerrit User 1188132 <1188132@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>