Update patch set 6
Patch Set 6:

This CL has failed the run. Reason:

Tryjob [v8/try/v8_win64_msvc_light_compile_rel](https://cr-buildbucket.appspot.com/build/8791540045797100721) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[479/955] CXX obj/v8_base_without_compiler/memory-reducer.obj
FAILED: obj/v8_base_without_compiler/memory-reducer.obj
ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
cl : Command line warning D9025 : overriding '/std:c++20' with '/std:c++17'
../../src/heap/memory-reducer.cc(55): error C7555: use of designated initializers requires at least '/std:c++20'
../../src/heap/memory-reducer.cc(106): error C7555: use of designated initializers requires at least '/std:c++20'
../../src/heap/memory-reducer.cc(130): error C7555: use of designated initializers requires at least '/std:c++20'
```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 6
Tag: autogenerated:cq:dry-run:1674129393
Attention: {"person_ident":"Gerrit User 1357035 \u003c1357035@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: Tryjobs failed"}