Update patch set 2
Patch Set 2:

Failed builds:
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8873880646851179792
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [990/1241] CXX obj/test/unittests/unittests_sources/function-body-decoder-unittest.obj
    FAILED: obj/test/unittests/unittests_sources/function-body-decoder-unittest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../../test/unittests/wasm/function-body-decoder-unittest.cc(4154): error C2398: Element '9': conversion from 'v8::internal::wasm::HeapType::Representation' to 'const v8::internal::byte' requires a narrowing conversion
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8873879210310917216
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [20/105] CXX obj/test/unittests/unittests_sources/function-body-decoder-unittest.obj
    FAILED: obj/test/unittests/unittests_sources/function-body-decoder-unittest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../../test/unittests/wasm/function-body-decoder-unittest.cc(4154): error C2398: Element '9': conversion from 'v8::internal::wasm::HeapType::Representation' to 'const v8::internal::byte' requires a narrowing conversion
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1411293 \u003c1411293@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"reviewer or cc replied"}