Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.v8.try/v8_linux_rel_ng JOB_FAILED https://cr-buildbucket.appspot.com/build/8877155972947301520
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [340/1301] CXX obj/v8_base_without_compiler/frames.o
    FAILED: obj/v8_base_without_compiler/frames.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../src/execution/frames.cc:5:
    In file included from ../../src/execution/frames.h:8:
    In file included from ../../src/codegen/safepoint-table.h:11:
    In file included from ../../src/utils/utils.h:23:
    ../../src/utils/vector.h:289:10: fatal error: recursive template instantiation exceeded maximum depth of 1024
    return {start, size};
    ^
    ../../src/utils/vector.h:304:10: note: in instantiation of function template specialization 'v8::int...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_linux_noi18n_compile_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8877155972947301536
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [388/1332] CXX obj/v8_base_without_compiler/builtins-date.o
    FAILED: obj/v8_base_without_compiler/builtins-date.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    In file included from ../../src/builtins/builtins-date.cc:17:
    ../../src/strings/string-stream.h:160:17: error: no matching function for call to 'VectorOf'
    Add(format, VectorOf({args...}));
    ^~~~~~~~
    ../../src/strings/string-stream.h:155:5: note: in instantiation of function template specialization 'v8::internal::StringStream::Add<const char *, const char *, int, int>' requested here
    Add(CStrVector(format), args...);
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_linux_gcc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8877155972947301552
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [404/1903] CXX obj/v8_base_without_compiler/builtins-date.o
    FAILED: obj/v8_base_without_compiler/builtins-date.o
    /b/s/w/ir/cache/goma/client/gomacc g++ -MMD -MF obj/v8_base_without_compiler/builtins-date.o.d -DUSE...(too long)
    In file included from ../../src/builtins/builtins-date.cc:17:0:
    ../../src/strings/string-stream.h: In instantiation of 'void v8::internal::StringStream::Add(v8::internal::Vector<const char>, Args ...) [with Args = {const char*, const char*, int, int}]':
    ../../src/strings/string-stream.h:155:5:   required from 'void v8::internal::StringStream::Add(const char*, Args ...) [with Args = {const char*, const char*, int, int}]'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run