Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8888017829081418288
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1465/1523] CXX obj/test/cctest/cctest_sources/test-liftoff-inspection.obj
    FAILED: obj/test/cctest/cctest_sources/test-liftoff-inspection.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../../test/cctest/wasm/test-liftoff-inspection.cc(182): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../test/cctest/wasm/test-liftoff-inspection.cc(193): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8888015962625760032
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [51/55] CXX obj/test/cctest/cctest_sources/test-liftoff-inspection.obj
    FAILED: obj/test/cctest/cctest_sources/test-liftoff-inspection.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../../test/cctest/wasm/test-liftoff-inspection.cc(182): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../test/cctest/wasm/test-liftoff-inspection.cc(193): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run