Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > (2 comments)
> > 
> > > Patch Set 1:
> > > 
> > > (1 comment)
> > > 
> > > > Patch Set 1:
> > > > 
> > > > (3 comments)
> > > > 
> > > > > Patch Set 1:
> > > > > 
> > > > > Dmitry, I need help with updating the inspector protocol. How do I generate the new protocol from the pdl file? Is there something I need to build? Is this the right way to update the protocol?
> > > > 
> > > > Code should be generated during normal build for you, e.g. build inspector tests. This is the right way to update the protocol. If you have any cryptic compiler errors, I'll be glad to help.
> > > 
> > > I see this error when building inspector-test:
> > > In file included from ../../src/inspector/inspected-context.cc:8:                                                                                              
> > > ../../src/inspector/injected-script.h:90:46: error: no member named 'PrivateFieldDescriptor' in namespace 'v8_inspector::protocol::Runtime'                    
> > >           protocol::Array<protocol::Runtime::PrivateFieldDescriptor>>* result);                                                                                
> > >                           ~~~~~~~~~~~~~~~~~~~^                                  
> > > 
> > > This seems like the c++ files aren't generated?
> > 
> > I think that's because PrivateFieldDescriptor is not actually referenced in any method/event. Once you do, it should be generated.
> 
> I reference it here https://chromium-review.googlesource.com/c/v8/v8/+/1487914/1/src/inspector/injected-script.cc and https://chromium-review.googlesource.com/c/v8/v8/+/1487914/1/src/inspector/v8-runtime-agent-impl.cc. Should it be referenced from somewhere else?

I mean, in the protocol file. You should use the type in Runtime.getProperties so that it's generated and that will also update getProperties() signature which V8RuntimeAgentImpl overrides.

Patch-set: 1
Reviewer: Gerrit User 1000379 <1000379@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>