Update patch set 6
Patch Set 6:

Failed builds:
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8875895446769061584
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [84/106] CXX obj/test/cctest/cctest_sources/test-gc.obj
    FAILED: obj/test/cctest/cctest_sources/test-gc.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../../test/cctest/wasm/test-gc.cc(382): error C2398: Element '21': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ../../test/cctest/wasm/test-gc.cc(391): error C2398: Element '36': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ```
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8875894742803692368
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [80/107] CXX obj/test/cctest/cctest_sources/test-gc.obj
    FAILED: obj/test/cctest/cctest_sources/test-gc.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../../test/cctest/wasm/test-gc.cc(382): error C2398: Element '21': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ../../test/cctest/wasm/test-gc.cc(391): error C2398: Element '36': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 6
Tag: autogenerated:cq:full-run