Remove a useless typedef in wasm-js.cc
This breaks the MSVC build of Chrome with the following message:

c:\src\chrome\src\out\debug\gen\base\trace_event\common\../../../../../../v8/src/wasm/wasm-js.cc(76): error C2872: 'byte': ambiguous symbol
c:\src\chrome\src\out\debug\gen\base\trace_event\common\../../../../../../v8/src/wasm/wasm-js.cc(25): note: could be 'uint8_t byte'
C:\src\chrome\src\v8\src/globals.h(141): note: or       'v8::internal::byte'

This typedef is already defined in src/globals.h: https://cs.chromium.org/chromium/src/v8/src/globals.h?l=141&rcl=07259a9ceafa078c9bb7f9ee1bb6f2d67256cc80

Bug: chromium:683729