Update patch set 3
Patch Set 3:

I think this change broke the build with MSVC.
It now errors with:

11:04:55 c:\ws\deps\v8\src\wasm\value-type.h(113): error C2398: Element '1': conversion from 'int' to 'const uint8_t' requires a narrowing conversion [c:\ws\tools\v8_gypfiles\v8_initializers.vcxproj]
11:04:55 c:\ws\deps\v8\src\wasm\value-type.h(113): error C2398: Element '2': conversion from 'int' to 'const uint8_t' requires a narrowing conversion [c:\ws\tools\v8_gypfiles\v8_initializers.vcxproj]
...

Patch-set: 3
CC: Gerrit User 1158669 <1158669@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>