Update patch set 1
Patch Set 1:

RevisionConflictException: Failed to submit 1 change due to the following problems:
Change 1167522: Patch set ref refs/changes/22/1167522/1 not found. Expected patch set ref of 1 to point to revision b57f28e6948e164c3fe0dd4c7e75beef1ce9a1cf

Patch-set: 1
Tag: autogenerated:cq:full-run
Reviewer: Gerrit User 1111084 <1111084@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>