Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > > Patch Set 4:
> > > 
> > > > Patch Set 4:
> > > > 
> > > > Did you look at the bot failures? The current one is
> > > > 
> > > > ../../test/unittests/compiler/machine-operator-reducer-unittest.cc:1962:58: error: use of undeclared identifier 'Pow'; did you mean 'pow'?
> > > >                   IsFloat64Constant(NanSensitiveDoubleEq(Pow(x, y))));
> > > >                                                          ^~~
> > > >                                                          pow
> > > > ../../third_party/googletest/src/googlemock/include/gmock/gmock-matchers.h:4449:60: note: expanded from macro 'EXPECT_THAT'
> > > >     ::testing::internal::MakePredicateFormatterFromMatcher(matcher), value)
> > > >                                                            ^
> > > > ../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:113:23: note: expanded from macro 'EXPECT_PRED_FORMAT1'
> > > >   GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_NONFATAL_FAILURE_)
> > > >                       ^
> > > > ../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:100:17: note: expanded from macro 'GTEST_PRED_FORMAT1_'
> > > >   GTEST_ASSERT_(pred_format(#v1, v1), \
> > > >                 ^
> > > > ../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:76:52: note: expanded from macro 'GTEST_ASSERT_'
> > > >   if (const ::testing::AssertionResult gtest_ar = (expression)) \
> > > >                                                    ^
> > > > ../../build/linux/debian_sid_amd64-sysroot/usr/include/x86_64-linux-gnu/bits/mathcalls.h:140:17: note: 'pow' declared here
> > > > __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
> > > >                 ^
> > > > 1 error generated.
> > > 
> > > Also note one of the earlier patchsets only failed on the gcc builder.
> > 
> > Right now I'm building with `autoninja -j5 -C out/x64.release/` and then testing with `tools/run-tests.py --outdir=out/x64.release -j5`
> > 
> > What commands should I be using instead? How do I test with gcc? I don't want to keep CQing this to see if it works.
> 
> Click on the failing bots above, many will show the gn args they use somewhere. E.g. here: https://ci.chromium.org/p/v8/builders/luci.v8.try/v8_linux_rel_ng/b8924103176706226240
> 
> Your command above looks good, just tailor the gn args to whatever bot is failing.

Trying to build with is_clang=false gives me "unknown warning option '-Wno-maybe-uninitialized'" and I've tried with both apple gcc (which is still clang) and with actual gnu gcc.

Patch-set: 4
Reviewer: Gerrit User 1274103 <1274103@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>