Update patch set 6
Patch Set 6:

Dry run: Failed builds:
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8811798561341411089
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [59/1071] CXX obj/v8_init/setup-isolate-full.obj
    FAILED: obj/v8_init/setup-isolate-full.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../..\src/objects/api-callbacks-inl.h(125): error C2440: 'reinterpret_cast': cannot convert from 'v8::internal::Address' to 'v8::internal::Address'
    ../..\src/objects/api-callbacks-inl.h(125): note: Conversion is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast
    ../..\src/objects/api-callbacks-inl.h(125): error C2660: 'v8::internal::Object::WriteExternalPointerField': function does not take 3 arguments
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8811797607292982593
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [59/1071] CXX obj/d8/d8.obj
    FAILED: obj/d8/d8.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../..\src/objects/api-callbacks-inl.h(125): error C2440: 'reinterpret_cast': cannot convert from 'v8::internal::Address' to 'v8::internal::Address'
    ../..\src/objects/api-callbacks-inl.h(125): note: Conversion is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast
    ../..\src/objects/api-callbacks-inl.h(125): error C2660: 'v8::internal::Object::WriteExternalPointerField': function does not take 3 arguments
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 6
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1183889 \u003c1183889@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: CQ dry run failed."}