Update patch set 1
Patch Set 1:

RevisionConflictException: Failed to submit 1 change due to the following problems:
Change 1171003: Change could not be merged because the commit is empty. Project policy requires all commits to contain modifications to at least one file.

Patch-set: 1
Tag: autogenerated:cq:full-run
Reviewer: Gerrit User 1111084 <1111084@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>