Update patch set 3
Patch Set 3:

Dry run: Try jobs failed on following builders:
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://ci.chromium.org/b/8894548342249593680
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [35/2028] CXX obj/torque_base/source-positions.obj
    FAILED: obj/torque_base/source-positions.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../..\src/torque/utils.h(466): error C2220: the following warning is treated as an error
    ../..\src/torque/utils.h(466): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
    [36/2028] CXX obj/torque_base/csa-generator.obj
    FAILED: obj/torque_base/csa-generator.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run