[riscv64] Assembler::li_estimate() remove unused variable
Compiling for RISC-V with GCC 10.3 results in:

../../src/codegen/riscv64/assembler-riscv64.cc:2587:15: error:
variable ‘part’ set but not used [-Werror=unused-but-set-variable]
 2587 |       int32_t part;
      |               ^~~~

Remove the variable part as its value is unused.

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
Change-Id: Id0fcad815c1dd9ce5256e0f71c3d2db37e85931f