[parser] Provide better error when not closing function body
This patch changes the output from:
  function t(){
              ^
  SyntaxError: Unexpected end of input

to:

  function t(){
              ^
  SyntaxError: missing '}' after function body.

Bug: v8:6513, v8:7321
Change-Id: I50c12588abae08a9cfcca653e3988d154095b131