Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 1:
> > 
> > (1 comment)
> 
> Hello Ulan, thanks for your suggestion. After I try to decrease the kMaxRegularHeapObjectSize to 327680 on ppc, I found another static_assert failure.
> 
> In file included from ../../src/objects/string-table.h:8:
> ../../src/objects/hash-table.h:210:3: error: static_assert failed "EntryToIndex(kMaxRegularCapacity) < kMaxRegularLength"
>   STATIC_ASSERT(EntryToIndex(kMaxRegularCapacity) < kMaxRegularLength);
>   ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../src/base/macros.h:204:29: note: expanded from macro 'STATIC_ASSERT'
> 
> Any insights for this one?
> 
> Thanks again!
> John

There probably other constants that implicitly depend onthe kMaxRegularHeapObjectSize. In this case we need to also decrease the kMaxRegularCapacity to 16384 / 2.

Patch-set: 2
Reviewer: Gerrit User 1002405 <1002405@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>