Update patch set 4
Patch Set 4:

RevisionConflictException: Cannot rebase b4de9a15c21c95b7e18130d330fa017f99f46337: The change could not be rebased due to a conflict during merge.

Patch-set: 4
Tag: autogenerated:cq:full-run