Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> This breaks compilation on Windows VS2015, so it breaks nodejs:
> 
> ```
> "C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj" (Build target) (1) ->
> (ClCompile target) ->
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(88): error C3250: 'upper_half': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(89): error C3250: 'next_value': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(90): error C3250: 'add': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(91): error C3250: 'next_bits': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(92): error C3256: 'next_value': variable use does not produce a constant expression [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(92): error C3256: 'add': variable use does not produce a constant expression [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(76): error C3259: 'constexpr' functions can only have one return statement [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(120): error C3250: 'u': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(121): error C3256: 'u': variable use does not produce a constant expression [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
>   C:\workspace\node-compile-windows\deps\v8\src/base/bits.h(40): error C3250: 'mask': declaration is not allowed in 'constexpr' function body [C:\workspace\node-compile-windows\deps\v8\src\v8_init.vcxproj]
> 
>     51 Warning(s)
>     10 Error(s)
> ```

We recently had a similar issue with another nodejs bot: https://chromium-review.googlesource.com/c/v8/v8/+/728026
The solution there was to update the compile flags.
This case is more involved though as it seems that VS2015 does not support extended constexpr functions. They are explicitly allowed in our style guide though: https://chromium-cpp.appspot.com/#core-whitelist-14

+Michael Achenbach
Question: Do we only build with clang and msvc 2017 on windows nowadays?

Question to Refael: Any chance you can switch to msvc 2017?

Patch-set: 5
Reviewer: Gerrit User 1115956 <1115956@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>