cppgc: Fix chromium build with v8_use_perfetto.
The dependency on v8_tracing supplies include paths &
dependencies on the tracing library when built with
v8_use_perfetto. It doesn't add any dependencies
if v8_use_perfetto is false (e.g. in standalone builds).

This is an attempt to fix the linux-perfetto-rel builder [1], which is
currently erroring:

FAILED: obj/v8/cppgc_base/sweeper.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
In file included from ../../v8/src/heap/cppgc/sweeper.cc:24:
In file included from ../../v8/src/heap/cppgc/stats-collector.h:17:
In file included from ../../v8/src/heap/cppgc/trace-event.h:9:
In file included from ../../v8/src/tracing/trace-event.h:12:
gen/third_party/perfetto/protos/perfetto/trace/track_event/debug_annotation.pbzero.h:9:10: fatal error: 'perfetto/protozero/message.h' file not found
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[1] https://ci.chromium.org/p/chromium/builders/ci/linux-perfetto-rel

Bug: chromium:1056170
Change-Id: I1e1e9a58ce4a84cb74bdc0b15c1e90904453a9da