Update patch set 2
Patch Set 2:

(2 comments)

> Patch Set 2:
> 
> Actually, if we collect the keys along the chain, it also might be useful to include constructor names for every object along the chain.
> 
> Something like
> 
> Error: Converting circular structure to JSON
>     starting at Array
>     index 1: Array
>     index 4: Class1
>     property 'x': Class2
>     property 'y' closes the circle
>     
> Maybe Sathya has some opinion on this?

I like the idea of showing the entire path (if that's possible without perf regressions)!

It wasn't immediately clear to me that those were constructors when I first read it -- I'm slightly worried that this might be a lot of data visually that could be confusing initially.

Patch-set: 2
Reviewer: Gerrit User 1158954 <1158954@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>