Update patch set 5
Patch Set 5:

Failed builds:
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8875898676578833568
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1014/1232] CXX obj/test/cctest/cctest_sources/test-gc.obj
    FAILED: obj/test/cctest/cctest_sources/test-gc.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../../test/cctest/wasm/test-gc.cc(218): error C2398: Element '31': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ../../test/cctest/wasm/test-gc.cc(278): error C2398: Element '58': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ../../test/cctest/wasm/test-gc.cc(278): error C2398: Element '68': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.v8.try/v8_win64_msvc_compile_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8875896348323877312
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [35/241] CXX obj/test/cctest/cctest_sources/test-gc.obj
    FAILED: obj/test/cctest/cctest_sources/test-gc.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\v8\third_party\depot_tools\win_toolch...(too long)
    ../../test/cctest/wasm/test-gc.cc(218): error C2398: Element '31': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ../../test/cctest/wasm/test-gc.cc(278): error C2398: Element '58': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ../../test/cctest/wasm/test-gc.cc(278): error C2398: Element '68': conversion from 'uint32_t' to '_Ty' requires a narrowing conversion
    with
    [
    _Ty=uint8_t
    ]
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 5
Tag: autogenerated:cq:full-run